name: Release on main tags

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Set package name environment variable
        run: echo "jar_filename=$(./build.sh name)" >> $GITHUB_ENV
      - name: Build package
        run: ./build.sh package
      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ env.jar_filename }}
          draft: yes
          fail_on_unmatched_files: yes
